trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MYSQL_SERVER: 'iamusingtheserverforsql.database.windows.net'
  MYSQL_DATABASE: 'ARMTemplateDatabase'
  MYSQL_USER: 'IamOwner'
  MYSQL_PASSWORD: 'Iam@good'
  System.Debug: true

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install mysql-connector-python
    python AzureInfraandcodepipeline/push_test_data.py
  displayName: 'Install MySQL Connector and Run Script'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'testdata'
    publishLocation: 'pipeline'
  displayName: 'Publish Test Data Artifact'
